/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subnetapp;

import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kamal
 */
public class Nbr_Reseaux_Option extends javax.swing.JFrame {

    /**
     * Creates new form Nbr_Reseaux_Option
     */
    public Nbr_Reseaux_Option() {
        initComponents();
           this.imagePanel1.setImage(Toolkit.getDefaultToolkit().getImage("MainBackground2.jpg"));
      //  this.imagePanel1.setImage(new ImageIcon(this.getClass().getResource("MainBackground.jpg")).getImage());
      this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel1 = new subnetapp.ImagePanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Oct1 = new javax.swing.JTextField();
        txt_Oct2 = new javax.swing.JTextField();
        txt_Oct3 = new javax.swing.JTextField();
        txt_Oct4 = new javax.swing.JTextField();
        txt_mask1 = new javax.swing.JTextField();
        txt_mask2 = new javax.swing.JTextField();
        txt_mask3 = new javax.swing.JTextField();
        txt_mask4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Nbr_Subnet = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SubNetApp");
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(400, 250));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        jButton2.setText("Effacer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createSequentialGroup()
                .addContainerGap(407, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(29, 29, 29))
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(89, 89, 89))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Adresse IP : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Masque de sous reseau : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Nombre de sous reseaux : ");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("VOIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Oct1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(txt_mask1))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Oct2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                    .addComponent(txt_mask2))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Oct3, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(txt_mask3))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Oct4, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(txt_mask4)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(txt_Nbr_Subnet, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Oct3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txt_Oct1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_Oct4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_Oct2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_mask1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mask2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mask3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mask4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Nbr_Subnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int oct1 = Integer.parseInt(this.txt_Oct1.getText().trim());
        int oct2 = Integer.parseInt(this.txt_Oct2.getText().trim());
        int oct3 = Integer.parseInt(this.txt_Oct3.getText().trim());
        int oct4 = Integer.parseInt(this.txt_Oct4.getText().trim());

        int msk1 = Integer.parseInt(this.txt_mask1.getText().trim());
        int msk2 = Integer.parseInt(this.txt_mask2.getText().trim());
        int msk3 = Integer.parseInt(this.txt_mask3.getText().trim());
        int msk4 = Integer.parseInt(this.txt_mask4.getText().trim());

        int nbr_de_sous_res = Integer.parseInt(this.txt_Nbr_Subnet.getText().trim());

        int[] ip_saisi = {oct1, oct2, oct3, oct4};
        int[] msk_saisi = {msk1, msk2, msk3, msk4};
        
       // MyException.checkIp(ip_saisi);
       // MyException.checkMask(msk_saisi);
        
         if(MyException.checkIp(ip_saisi).matches("") & MyException.checkMask(msk_saisi).matches("") & MyException.chekSubNetSize(ip_saisi, msk_saisi, nbr_de_sous_res).matches("")){
             
              IP ip = new IP();
        ip.setIP_DEC(ip_saisi);
        ip.setMASK_DEC(msk_saisi);
        
        //test app
        int[] newMask = ip.getNewMask(ip_saisi, msk_saisi, nbr_de_sous_res);
        int nbrOfSubnet = Calculer.puissance(2, Calculer.getNbrBitEmprunt(nbr_de_sous_res));

        int[] firstSubnet = ip.getNetId(ip_saisi, msk_saisi);
        int[] firstSubnet32bit = ip.concat(ip.convertToIpBin(firstSubnet));
        int[] hopeBin32bit = ip.getHopeBin32bit(ip.getNbrBitInUserId(newMask));
        int NbrBitInUserId=ip.getNbrBitInUserId(newMask);
        
          
     
       ArrayList<int[]> allSubnet=ip.getAllSubnet(ip_saisi, msk_saisi, nbr_de_sous_res);
        
      
        
         Object[] tablesColumnNames=new Object[6];
        
        tablesColumnNames[0]="SubnetId";
        tablesColumnNames[1]="SubnetAddress";
        tablesColumnNames[2]="NewMask";
        tablesColumnNames[3]="NbrOfUseAddr";
        tablesColumnNames[4]="firstAddr";
        tablesColumnNames[5]="lastAddr";
        
        DefaultTableModel tbd=new DefaultTableModel();
        tbd.setColumnIdentifiers(tablesColumnNames);
        
          Object[] RowItem=new Object[6];
        
        for(int i=0;i<allSubnet.size();i++){
            RowItem[0] = i;
            RowItem[1] = ip.getIptoString(allSubnet.get(i));
            RowItem[2] = ip.getIptoString(ip.getNewMask(ip_saisi, msk_saisi, nbr_de_sous_res));
            RowItem[3] = ip.getNbrOfUseAddr(ip.getNewMask(ip_saisi, msk_saisi, nbr_de_sous_res));
            RowItem[4] = ip.getIptoString(ip.getFirstAddress(allSubnet.get(i), ip.getNewMask(ip_saisi, msk_saisi, nbr_de_sous_res)));
            RowItem[5] = ip.getIptoString(ip.getLastAddress(allSubnet.get(i), ip.getNewMask(ip_saisi, msk_saisi, nbr_de_sous_res)));
            
            tbd.addRow(RowItem);
        }
         Resultats result=new Resultats();
         
          result.setIconImage(new ImageIcon("subnetIcon.png").getImage());
        
        result.setVisible(true);
        result.pack();
        result.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       // cidr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       // this.setVisible(false);
        
        result.getjTable1().setModel(tbd);
       
             
         }else {
//             this.txt_Oct1.setText("");
//             this.txt_Oct2.setText("");
//             this.txt_Oct3.setText("");
//             this.txt_Oct4.setText("");
//             
//             this.txt_mask1.setText("");
//             this.txt_mask2.setText("");
//             this.txt_mask3.setText("");
//             this.txt_mask4.setText("");
//             
//             this.txt_Nbr_Subnet.setText("");
             MyException.setMsgErrors("");
             
       
         }
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.txt_Oct1.setText("");
        this.txt_Oct2.setText("");
        this.txt_Oct3.setText("");
        this.txt_Oct4.setText("");

        this.txt_mask1.setText("");
        this.txt_mask2.setText("");
        this.txt_mask3.setText("");
        this.txt_mask4.setText("");

        this.txt_Nbr_Subnet.setText("");
        
        MyException.setMsgErrors("");
        
        this.txt_Oct1.requestFocusInWindow();
             
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nbr_Reseaux_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nbr_Reseaux_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nbr_Reseaux_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nbr_Reseaux_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nbr_Reseaux_Option().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private subnetapp.ImagePanel imagePanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_Nbr_Subnet;
    private javax.swing.JTextField txt_Oct1;
    private javax.swing.JTextField txt_Oct2;
    private javax.swing.JTextField txt_Oct3;
    private javax.swing.JTextField txt_Oct4;
    private javax.swing.JTextField txt_mask1;
    private javax.swing.JTextField txt_mask2;
    private javax.swing.JTextField txt_mask3;
    private javax.swing.JTextField txt_mask4;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxt_Oct1() {
        return txt_Oct1;
    }

    public void setTxt_Oct1(JTextField txt_Oct1) {
        this.txt_Oct1 = txt_Oct1;
    }
}
